### ISSUE TITLE
Remove reference to m1.small

### ISSUE THREAD

**Issue by smaffulli** [dreamhost/dreamcloud-docs#128]
Article https://help.dreamhost.com/hc/en-us/articles/215912848 needs some updates, since it may be an openstack default one and mentions things like "m1.small" flavor size. It is also quite wordy and lacks screenshots.

**Comment by squidboylan** [comment]
https://github.com/dreamhost/openstack-manuals/pull/5 fixes this, it's in the repo we forked from upstream
