### ISSUE TITLE
Disable/remove article with duplicate content

### ISSUE THREAD

**Issue by Bullfrog117** [dreamhost/dreamcloud-docs#130]
\[[DreamHost > DreamCompute Cloud Servers > Basics > How to create and manage volumes with the DreamCompute dashboard](https://help.dreamhost.com/hc/en-us/articles/215912858-How-to-create-and-manage-volumes-with-the-DreamCompute-dashboard)\] (#215912858) looks like it was pulled straight from OpenStack and it's title is VERY similar to \[[DreamHost > DreamCompute Cloud Servers > Advanced Tutorials > How to create and mount volumes on DreamCompute](https://help.dreamhost.com/hc/en-us/articles/221778268-How-to-create-and-mount-volumes-on-DreamCompute)\] (#221778268) which is a **much** more clearly written article. 

To avoid confusion, I kindly request that the "How to create and manage volumes with the DreamCompute dashboard" article (#215912858) be either disabled, removed, or renamed.

**Comment by smaffulli** [comment]
Yeah, good catch @Bullfrog117 . We should be more careful when adding content and make sure there isn't something else that could be fixed instead: now we need to decide how to remove one without creating issues (like broken links).

**Comment by squidboylan** [comment]
Thanks for this heads up, I've moved the less informative article into the "Draft" state, which basically means it isn't publicly viewable but is still stored in Zendesk. We will do our best to prevent this in the future.
