### ISSUE TITLE
Incorrect URL for "How to upload an SSH key via the web UI" in "How to launch and manage servers with the DreamCompute dashboard"

### ISSUE THREAD

**Issue by Bullfrog117** [dreamhost/dreamcloud-docs#48]
https://help.dreamhost.com/hc/en-us/articles/215912848-How-to-launch-and-manage-servers-with-the-DreamCompute-dashboard

If you don’t already have an SSH key, you can find out how to create one. 

"how to create one" links to 'https://help.dreamhost.com/articles/214843617', but should link to 'https://help.dreamhost.com/hc/en-us/articles/214843617' (missing /hc/en-us/ in the middle).

**Comment by justinlund** [comment]
Good catch! Just pushed a fix.

**Comment by Bullfrog117** [comment]
Looks good to me! Thanks, @justinlund! :-D
